### ISSUE TITLE
Attempting to run bootstrapped kurtosis-go repository gives error for unbound variable

### ISSUE THREAD

**Issue by galenmarchetti** [kurtosis-tech/kurtosis-go#83]
Bootstrapping kurtosis-go repository, in step 4 of "Run your testsuite" on https://docs.kurtosistech.com/quickstart.html, console returns `./scripts/build_and_run.sh: line 101: @: unbound variable` 

note: I was able to fix this locally by manually commenting out `build_and_run.sh` line 1: `#set -euo pipefail`

**Comment by mieubrisse** [comment]
Fixed
